-- SALES & PAYMENT ANALYSIS
-- Topics:
-- COUNT(), SUM(), AVG(), MIN(), MAX()

-- Select Database
USE sakila;

-- VIEW COMPLETE PAYMENT TABLE
SELECT *
FROM payment;

-- TOTAL NUMBER OF PAYMENTS
SELECT COUNT(*) AS Total_Payments
FROM payment;

-- TOTAL NUMBER OF CUSTOMERS WHO MADE PAYMENTS
SELECT COUNT(DISTINCT customer_id) AS Total_Customers
FROM payment;

-- TOTAL REVENUE GENERATED
SELECT SUM(amount) AS Total_Revenue
FROM payment;

-- AVERAGE PAYMENT AMOUNT
SELECT AVG(amount) AS Average_Payment
FROM payment;

-- HIGHEST PAYMENT RECEIVED
SELECT MAX(amount) AS Highest_Payment
FROM payment;

-- LOWEST PAYMENT RECEIVED
SELECT MIN(amount) AS Lowest_Payment
FROM payment;

-- TOTAL NUMBER OF TRANSACTIONS
SELECT COUNT(payment_id) AS Total_Transactions
FROM payment;

-- TOTAL REVENUE GENERATED BY STAFF
SELECT staff_id, SUM(amount) AS Revenue
FROM payment
GROUP BY staff_id;

-- AVERAGE PAYMENT HANDLED BY EACH STAFF
SELECT staff_id, AVG(amount) AS Average_Payment
FROM payment
GROUP BY staff_id;

-- MAXIMUM PAYMENT HANDLED BY EACH STAFF
SELECT staff_id, MAX(amount) AS Highest_Payment
FROM payment
GROUP BY staff_id;

-- MINIMUM PAYMENT HANDLED BY EACH STAFF
SELECT staff_id, MIN(amount) AS Lowest_Payment
FROM payment
GROUP BY staff_id;

-- TOTAL PAYMENTS MADE ON EACH DATE
SELECT payment_date,
COUNT(*) AS Payments
FROM payment
GROUP BY payment_date
ORDER BY payment_date;

-- TOP 10 HIGHEST PAYMENTS
SELECT payment_id, customer_id, amount
FROM payment
ORDER BY amount DESC
LIMIT 10;
