/*
CUSTOMERS AND PRODUCTS ANALYSIS USING SQL
PROGRAM 4:Advanced Customer & Sales Analytics

Manager's Final Assignment: Generate advanced business reports
*/

USE RetailAnalytics;

-- =====================================================
-- SECTION A : CUSTOMER & ORDER ANALYSIS
-- =====================================================

-- Task 1 Display every customer with their orders.
SELECT c.customer_id, c.customer_city, o.order_id, o.order_status
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id;

-- Task 2 Display customers who have never placed an order.

SELECT c.customer_id, c.customer_city
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;

-- Task 3 Count orders placed by each customer.
SELECT c.customer_id,
COUNT(o.order_id) AS Total_Orders
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id
ORDER BY Total_Orders DESC;

-- Task 4 Display Top 10 customers with highest orders.
SELECT c.customer_id,
COUNT(o.order_id) AS Total_Orders
FROM customers c
INNER JOIN orders o ON c.customer_id=o.customer_id
GROUP BY c.customer_id
ORDER BY Total_Orders DESC
LIMIT 10;

-- =====================================================
-- SECTION B : PRODUCT SALES ANALYSIS
-- =====================================================

-- Task 5 Display products purchased in each order.
SELECT oi.order_id, oi.product_id, p.product_category_name
FROM order_items oi
INNER JOIN products p ON oi.product_id=p.product_id;

-- Task 6 Count products sold in each category.
SELECT p.product_category_name,
COUNT(*) AS Products_Sold
FROM order_items oi
INNER JOIN products p ON oi.product_id=p.product_id
GROUP BY p.product_category_name
ORDER BY Products_Sold DESC;

-- Task 7 Display Top 10 selling categories.
SELECT p.product_category_name,
COUNT(*) AS Sales
FROM order_items oi
INNER JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_category_name
ORDER BY Sales DESC
LIMIT 10;

-- =====================================================
-- SECTION C : PAYMENT ANALYSIS
-- =====================================================

-- Task 8 Revenue generated by each payment method.
SELECT payment_type, SUM(payment_value) AS Revenue
FROM olist_order_payments_dataset
GROUP BY payment_type
ORDER BY Revenue DESC;

-- Task 9 Average payment by payment method.

SELECT payment_type, AVG(payment_value) AS Average_Payment
FROM order_payments
GROUP BY payment_type;

-- Task 10 Orders with payment details.
SELECT o.order_id, o.order_status, p.payment_type, p.payment_value
FROM orders o
INNER JOIN order_payments p ON o.order_id=p.order_id;

-- =====================================================
-- SECTION D : SUBQUERY ANALYSIS
-- =====================================================

-- Task 11 Payments greater than average payment.
SELECT *
FROM order_payments
WHERE payment_value > (
    SELECT AVG(payment_value)
    FROM order_payments
);

-- Task 12 Highest payment transaction.
SELECT *
FROM order_payments
WHERE payment_value = (
    SELECT MAX(payment_value)
    FROM order_payments
);

-- Task 13 Products heavier than average weight.
SELECT *
FROM products
WHERE product_weight_g > (
    SELECT AVG(product_weight_g)
    FROM products
);

-- Task 14 Customers having more than average number of orders.
SELECT customer_id,
COUNT(order_id) AS Total_Orders
FROM orders
GROUP BY customer_id
HAVING COUNT(order_id) > (
    SELECT AVG(OrderCount)
    FROM (
        SELECT COUNT(order_id) AS OrderCount
        FROM orders
        GROUP BY customer_id
    ) AS CustomerOrders
);

-- =====================================================
-- SECTION E : BUSINESS INSIGHTS
-- =====================================================

-- Task 15 Top 10 highest payment transactions with customer city.
SELECT c.customer_city, o.order_id, p.payment_value
FROM customers c
INNER JOIN orders o ON c.customer_id=o.customer_id
INNER JOIN olist_order_payments_dataset p ON o.order_id=p.order_id
ORDER BY p.payment_value DESC
LIMIT 10;

-- Task 16 States having highest number of customers
SELECT customer_state,
COUNT(*) AS Total_Customers
FROM customers_dataset
GROUP BY customer_state
ORDER BY Total_Customers DESC;

-- Task 17 Payment methods generating revenue above average.
SELECT payment_type, SUM(payment_value) AS Revenue
FROM order_payments
GROUP BY payment_type
HAVING SUM(payment_value) > (
    SELECT AVG(TotalRevenue)
    FROM (
        SELECT SUM(payment_value) AS TotalRevenue
        FROM order_payments
        GROUP BY payment_type
    ) AS RevenueTable
);

-- Task 18 Display Top 5 cities having maximum orders.
SELECT c.customer_city,
COUNT(o.order_id) AS Orders
FROM customers c
INNER JOIN olist_orders_dataset o ON c.customer_id=o.customer_id
GROUP BY c.customer_city
ORDER BY Orders DESC
LIMIT 5;

/*
CONGRATULATIONS!
You have successfully completed the
CUSTOMERS AND PRODUCTS ANALYSIS
USING SQL PROJECT.

You have now completed a complete
SQL Data Analytics mini-project
using a real-world e-commerce dataset.
*/
